
version: '3'
services:

  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8005:8005"
    environment:
      - PORT=8005
      - DATABASE_URL=$DATABASE_URL
    restart: "no"

  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "8006:8006"
    environment:
      - PORT=8006
      - DATABASE_URL=$DATABASE_URL
    restart: "no"
